<a href="https://colab.research.google.com/github/Akansha009/DataScience/blob/main/Numoy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
my_list=[1,2,4,5,6]
type(my_list)

list

In [7]:
np.array(my_list)
type(my_list)

list

In [9]:
my_list_1=[1,2,4,5,6]
my_list_2=[4,5,6,11,0]
my_list_3=[21,44,58,16,12]
arr_new=np.array([my_list_1,my_list_2,my_list_3])
print(arr_new)

[[ 1  2  4  5  6]
 [ 4  5  6 11  0]
 [21 44 58 16 12]]


In [11]:
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [13]:
arr_2=np.arange(1,20,2)
print(arr_2)

[ 1  3  5  7  9 11 13 15 17 19]


In [15]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [17]:
np.linspace(1,50,30, dtype='int')

array([ 1,  2,  4,  6,  7,  9, 11, 12, 14, 16, 17, 19, 21, 22, 24, 26, 28,
       29, 31, 33, 34, 36, 38, 39, 41, 43, 44, 46, 48, 50])

In [19]:
np.random.rand(3,5)#here 3 is the number of rows and 5 is the number of columns
#by default the range in random. rand is 0-1 (1 being exclusive)

array([[0.83971224, 0.04080026, 0.11667661, 0.92715093, 0.18778483],
       [0.83538682, 0.27346543, 0.36764515, 0.32005827, 0.00881748],
       [0.05772644, 0.10382535, 0.03545628, 0.4523088 , 0.46762594]])

In [20]:
np.random.randint(3,9,4) #here 3-9 is the range and 4 indicates the number of elements we want from this range

array([8, 8, 8, 4])